### PR TITLE
Add fact verification paper

### PR DESCRIPTION
**Pull request by FeiWang96**

### CODE REVIEW

**Comment by personalization-trap** [comment]
I think this paper is relevant. Which section of survey should I include the paper?

**Comment by FeiWang96** [comment]
> I think this paper is relevant. Which section of survey should I include the paper?

Row "TabFact" in Table 7 should be proper. The accuracy we reported is 82.1.

```
@inproceedings{wang2021table,
  title={Table-based Fact Verification With Salience-aware Learning},
  author={Wang, Fei and Sun, Kexuan and Pujara, Jay and Szekely, Pedro and Chen, Muhao},
  booktitle={Findings of the Association for Computational Linguistics: EMNLP 2021},
  pages={4025--4036},
  year={2021}
}
```

**Comment by personalization-trap** [comment]
I agree. Can you resolve the conflicts so that I can merge your request?

**Comment by FeiWang96** [comment]
> I agree. Can you resolve the conflicts so that I can merge your request?

Fixed.

**Comment by personalization-trap** [comment]
I merged. It would be great if you can star the repo so that it can reach to more people in the field.

**Comment by FeiWang96** [comment]
> I merged. It would be great if you can star the repo so that it can reach to more people in the field.

Of course.

**Pull request merged**
