### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zachary62**
Thanks for contacting us! We've added the following works:

1. **Table Profiling:** Cocoon: Semantic Table Profiling Using Large Language Models 
2. **Table Transformation:** Relationalizing Tables with Large Language Models: The Promise and Challenges
3. **Entity Matching:** Disambiguate Entity Matching using Large Language Models through Relation Discovery

### CODE REVIEW

**Comment by personalization-trap** [comment]
I think the paper is relevant. Can you write a short description of it so that it makes it easier for us to write it in the next version? Also, which section of survey should I include the paper?

**Comment by zachary62** [comment]
**Short desc:**

(1) Cocoon: Semantic Table Profiling Using Large Language Models
Data profilers are crucial in identifying quality issues like missing or erroneous values for data analysis. Traditional statistical methods often lead to false positives and negatives. Cocoon integrates LLMs to add semantic understanding to statistical profiling. It decomposes the profiling into a three-step process: Semantic Context, Semantic Profile, and Semantic Review. User studies demonstrate Cocoon's effectiveness in accurately identifying issues in real-world datasets.

(2) Relationalizing Tables with Large Language Models: The Promise and Challenges
This study explores how GPT-3.5, GPT-4, and advanced prompting techniques affect the accuracy of table relationalization. GPT-4 with Task Decomposition and Chain-of-Thought achieves 74.6% accuracy. After addressing benchmark ambiguities, GPT-4's accuracy improves to 86.9% (whereas previous SOTA achieved 57.0%).

(3)  Disambiguating Entity Matching using Large Language Models through Relation Discovery
Entity matching has traditionally focused on fuzzy term matching, where LLMs have shown great accuracy. However, when integrating with external databases, exact matches are rare as entities have varying levels of detail and granularity. The core challenge with LLMs is disambiguating what "match" means. This work proposes a human-in-the-loop approach to disambiguate matches using categories of relations. We demonstrated its effectiveness through a case study on ESG reporting.

**Which section:**

A new Prompt Engineering "task decomposition" under 2.3 for (1), (2)
The gist of (1) and (2) is to decompose challenging data tasks into pieces manageable by LLMs, for data profiling and relationalization.
(Related to 5.3.3 Multi-turn, but these are specific for QA)

The prompt engineering for (3) is more unique.
At a high level, the original NL question is ambiguous.
We disambiguate the NL for the task of entity matching.
Maybe call it "Prompt Disambiguation" under 2.3.
(3) may also be a type of Query intent disambiguation for QA under 5.3.1

**Comment by personalization-trap** [comment]
I agree. Can you resolve the conflicts so that I can merge your request?

**Comment by zachary62** [comment]
I think the conflicts are resolved

**Pull request merged**
