### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by mojsaeed**
Thanks for contacting me! I've added some papers (mine and others that might be interesting). Here are more papers but I did not know where was the best place to put them in the readme:

### Tabular Data Benchmarking:
* [QATCH: Benchmarking SQL-centric tasks with Table Representation Learning Models on Your Data](https://proceedings.neurips.cc/paper_files/paper/2023/file/62a24b69b820d30e9e5ad4f15ff7bf72-Paper-Datasets_and_Benchmarks.pdf)
* [STARK: Benchmarking LLM Retrieval on Textual and Relational Knowledge Bases](https://arxiv.org/pdf/2404.13207)

### Tabular Representation:
* [Tables as Texts or Images: Evaluating the Table Reasoning Ability of LLMs and MLLMs](https://arxiv.org/pdf/2402.12424)

### Text2SQL:
You mentioned that you are surveying LLMs with at least 1 billion parameters. We have a Text2SQL system called [Scrutinizer](https://arxiv.org/pdf/2003.06708) that is applied on a document-level with an active learning algorithm. The system has 4 BERT models (which in total is more than 1B parameters), but not sure if that counts or not.

Thanks,
Mohammed

### CODE REVIEW

**Comment by personalization-trap** [comment]
I think the paper is relevant. Can you write a short description of it so that it makes it easier for us to write it in the next version? Also, which section of survey should I include the paper? Also can you resolve the conflict so that I can merge it?

**Comment by mojsaeed** [comment]
Hi again. Would it be possible to add some new sections in the README?
I will provide the details you mentioned in the next push.

**Comment by personalization-trap** [comment]
Can you resolve the conflict so that we can merge?

**Comment by mojsaeed** [comment]
Done

**Pull request merged**
