### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zwq2018**
Thanks for contacting me and bringing me to such an excellent survey!
I add a paper for LLM on data analysis
Data-Copilot: Bridging Billions of Data and Humans with Autonomous Workflow

### CODE REVIEW

**Comment by personalization-trap** [comment]
I think the paper is relevant. Can you write a short description of it so that it makes it easier for us to write it in the next version? Also, which section of survey should I include the paper?

**Comment by zwq2018** [comment]
> I think the paper is relevant. Can you write a short description of it so that it makes it easier for us to write it in the next version? Also, which section of the survey should I include in the paper?

Thank you.
Data-Copilot employs a data exploration phase on massive tables to design more universal and error-free interfaces for management and then invokes these interfaces to solve real-time data analysis tasks in the real world.

Our Data-Copilot is a data analytics agent, you can put it in the paper 2.3 Prompt Engineering, 2.4 End-to-end systems or 5. table understanding is more reasonable.

**Comment by personalization-trap** [comment]
I merged. It would be great if you can star the repo so that it can reach to more people in the field.

**Comment by zwq2018** [comment]
> I merged. It would be great if you can star the repo so that it can reach to more people in the field.

ok. Thanks, I already star the repo

**Pull request merged**
