### PR TITLE
Add table-to-text paper

### PR DESCRIPTION
**Pull request by FeiWang96**

### CODE REVIEW

**Comment by personalization-trap** [comment]
I think this paper is relevant. Which section of survey should I include the paper?

**Comment by FeiWang96** [comment]
> I think this paper is relevant. Which section of survey should I include the paper?

Row "ToTTo" in Table 7 should be proper. The BLEU score we reported is 48.4.

```
@inproceedings{wang2022robust,
  title={Robust (Controlled) Table-to-Text Generation with Structure-Aware Equivariance Learning},
  author={Wang, Fei and Xu, Zhewei and Szekely, Pedro and Chen, Muhao},
  booktitle={Proceedings of the 2022 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies},
  pages={5037--5048},
  year={2022}
}
```

**Comment by personalization-trap** [comment]
I agree. Can you resolve the conflicts so that I can merge your request?

**Comment by FeiWang96** [comment]
> I agree. Can you resolve the conflicts so that I can merge your request?

Fixed.

**Pull request merged**
